---
- hosts: local
  connection: local
  tasks:
  - wait_for:
      host: "127.0.0.1"
      port: "{{ item }}"
      state: started
      timeout: 0      
    register: result
    failed_when: no
    with_sequence: start=65535 end=1 stride=-1
    
  - debug: msg="{{ hosts }}"
